version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:23.9.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t playwright-tests .
      - run:
          name: Run Playwright tests
          command:  |
            mkdir -p test-results playwright-report
            npx playwright test tests/ui/01_Login --output=test-results --reporter=html

      # Store test artifacts (e.g., screenshots, videos, traces)
      - store_artifacts:
          path: test-results/
          destination: playwright-test-results
          when: on_fail

      # Store Playwright HTML report
      - store_artifacts:
          path: playwright-report/
          destination: playwright-report
          when: always
          
workflows:
  run-build-and-test:
    jobs:
      - build-and-test
