version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:23.9.0
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t playwright-tests .
      - run:
          name: Run Playwright tests
          command: |
            docker run --rm \
              -e PLATFORM=dev \
              -v "$(pwd)/test-results:/app/test-results" \
              -v "$(pwd)/playwright-report:/app/playwright-report" \
              playwright-tests

workflows:
  run-build-and-test:
    jobs:
      - build-and-test
