version: 2.1

parameters:
  test_tag:
    type: string
    default: ""

jobs:
  build-and-test:
    docker:
      - image: cimg/node:23.9.0
    parameters:
      test_tag:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t playwright-tests .
      - run:
          name: Run Playwright tests
          command: |
           if [ "<< parameters.test_tag >>" = "" ]; then
              TEST_CMD="npx playwright test tests/ui/01_Login --reporter=list"
            else
              TEST_CMD="npx playwright test tests/ui/01_Login --grep "<< parameters.test_tag >>" --reporter=list"
            fi
             
            docker run --name playwright-container \
            -e PLATFORM=dev \
            playwright-tests $TEST_CMD

            TEST_EXIT_CODE=$?
            docker cp playwright-container:/app/playwright-report ./playwright-report || echo "Failed to copy report"
            exit $TEST_EXIT_CODE
      # - run:
      #     name: Copy Playwright report
      #     when: always
      #     command: docker cp playwright-container:/app/playwright-report ./playwright-report

      - store_artifacts:
          path: playwright-report
          destination: playwright-report
          when: always

workflows:
  run-build-and-test:
    jobs:
      - build-and-test:
          test_tag: << pipeline.parameters.test_tag >>



# version: 2.1

# jobs:
#   build-and-test:
#     docker:
#       - image: cimg/node:23.9.0
#     steps:
#       - checkout
#       - setup_remote_docker
#       - run:
#           name: Build Docker image
#           command: docker build -t playwright-tests .
#       - run:
#           name: Run Playwright tests
#           command: |
#             docker run --name playwright-container \
#               -e PLATFORM=dev playwright-tests npx playwright test tests/ui/01_Login --grep @UI --reporter=html
#       - run:
#           name: Copy Playwright report
#           command: docker cp playwright-container:/app/playwright-report ./playwright-report

#       - store_artifacts:
#           path: playwright-report
#           destination: playwright-report
          
# workflows:
#   run-build-and-test:
#     jobs:
#       - build-and-test

