version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:23.9.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t playwright-tests .
      - run:
          name: Run Playwright tests
          command:  |
            docker run --name playwright-container \
              -e PLATFORM=dev playwright-tests npx playwright test tests/ui/01_Login --reporter=html
      - run:
          name: Copy Playwright report
          command: docker cp playwright-container:/app/playwright-report ./playwright-report
      - store_artifacts:
          path: test-results/
          destination: playwright-test-results
          when: on_fail

      # Store Playwright HTML report
      - store_artifacts:
          path: playwright-report/
          destination: playwright-report
          when: always
          
workflows:
  run-build-and-test:
    jobs:
      - build-and-test
